jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/ethereum/hive
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          packages: "./hivesim ./cmd/hivechain ./cmd/hiveview"

orbs:
  go: circleci/go@1.5.0
version: 2.1
workflows:
  main:
    jobs:
      - test
      - 
