jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          failfast: true
          packages:
            - .
            - ./hivesim
            - ./cmd/hivechain
            - ./cmd/hiveview
orbs:
  go: circleci/go@x.y
version: 2.1
workflows:
  main:
    jobs:
      - test
